// <auto-generated />
using System;
using AzurLaneClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzurLaneClasses.Migrations
{
    [DbContext(typeof(AzurLaneDbContext))]
    [Migration("20210612203520_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("AzurLaneClasses.ALEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CN_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EN_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("JP_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext");

                    b.Property<Guid>("BaseStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultChibiImage")
                        .HasColumnType("longtext");

                    b.Property<string>("DefaultFullImage")
                        .HasColumnType("longtext");

                    b.Property<int?>("EquippableTypeSlot1")
                        .HasColumnType("int");

                    b.Property<int?>("EquippableTypeSlot2")
                        .HasColumnType("int");

                    b.Property<int?>("EquippableTypeSlot3")
                        .HasColumnType("int");

                    b.Property<bool>("HasLive2DModel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IconImage")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Level100RetrofitStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Level100StatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Level120RetrofitStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Level120StatsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("ShipId")
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailImage")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VoiceActor")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipClasses");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChibiImage")
                        .HasColumnType("longtext");

                    b.Property<string>("FullImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_Chinese")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_English")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_Japanese")
                        .HasColumnType("longtext");

                    b.Property<string>("ShipId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipSkins");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("Ammunition")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("AntiSubmarine")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Luck")
                        .HasColumnType("int");

                    b.Property<int>("OilConsumption")
                        .HasColumnType("int");

                    b.Property<int>("Oxygen")
                        .HasColumnType("int");

                    b.Property<int>("Reload")
                        .HasColumnType("int");

                    b.Property<string>("ShipId")
                        .HasColumnType("longtext");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Torpedo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipStats");
                });
#pragma warning restore 612, 618
        }
    }
}
