// <auto-generated />
using System;
using AzurLaneClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzurLaneClasses.Migrations
{
    [DbContext(typeof(AzurLaneDbContext))]
    [Migration("20210720134839_RetrofitFix")]
    partial class RetrofitFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("AzurLaneClasses.ALEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CN_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EN_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("JP_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AzurLaneClasses.ALToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<bool>("WriteGrant")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ALTokens");
                });

            modelBuilder.Entity("AzurLaneClasses.CampaignLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CN_Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Chapter")
                        .HasColumnType("int");

                    b.Property<string>("EN_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("JP_Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CampaignLevels");
                });

            modelBuilder.Entity("AzurLaneClasses.ConstructionPool", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("AR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BB")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BC")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CV")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CVL")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<bool>("DD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SS")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WisdomCubes")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("ConstructionPools");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("BaseStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultChibiImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DefaultFullImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EquippableTypeSlot1")
                        .HasColumnType("int");

                    b.Property<int>("EquippableTypeSlot2")
                        .HasColumnType("int");

                    b.Property<int>("EquippableTypeSlot3")
                        .HasColumnType("int");

                    b.Property<bool>("HasLive2DModel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IconImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Level100RetrofitStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level100StatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level120RetrofitStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level120StatsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("ShipId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VoiceActor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaseStatsId");

                    b.HasIndex("Level100RetrofitStatsId");

                    b.HasIndex("Level100StatsId");

                    b.HasIndex("Level120RetrofitStatsId");

                    b.HasIndex("Level120StatsId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipClasses");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChibiImage")
                        .HasColumnType("longtext");

                    b.Property<string>("FullImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_Chinese")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_English")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_Japanese")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ShipId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipSkins");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("Ammunition")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("AntiSubmarine")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Luck")
                        .HasColumnType("int");

                    b.Property<int>("OilConsumption")
                        .HasColumnType("int");

                    b.Property<int>("Oxygen")
                        .HasColumnType("int");

                    b.Property<int>("Reload")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Torpedo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipStats");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "BaseStats")
                        .WithMany()
                        .HasForeignKey("BaseStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level100RetrofitStats")
                        .WithMany()
                        .HasForeignKey("Level100RetrofitStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level100Stats")
                        .WithMany()
                        .HasForeignKey("Level100StatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level120RetrofitStats")
                        .WithMany()
                        .HasForeignKey("Level120RetrofitStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level120Stats")
                        .WithMany()
                        .HasForeignKey("Level120StatsId");

                    b.Navigation("BaseStats");

                    b.Navigation("Level100RetrofitStats");

                    b.Navigation("Level100Stats");

                    b.Navigation("Level120RetrofitStats");

                    b.Navigation("Level120Stats");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("Skins")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
