// <auto-generated />
using System;
using AzurLaneClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzurLaneClasses.Migrations
{
    [DbContext(typeof(AzurLaneDbContext))]
    [Migration("20210824115403_QuotesTable")]
    partial class QuotesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("AzurLaneClasses.ALEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("CN_Period")
                        .HasColumnType("longtext");

                    b.Property<string>("EN_Period")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLimited")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JP_Period")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AzurLaneClasses.ALToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastRequest")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<bool>("WriteGrant")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ALTokens");
                });

            modelBuilder.Entity("AzurLaneClasses.Barrage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Hull")
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Ships")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Barrages");
                });

            modelBuilder.Entity("AzurLaneClasses.CampaignLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CN_Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Chapter")
                        .HasColumnType("int");

                    b.Property<string>("EN_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("JP_Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CampaignLevels");
                });

            modelBuilder.Entity("AzurLaneClasses.ConstructionPool", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("AR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BB")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BC")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CV")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CVL")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<bool>("DD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SS")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WisdomCubes")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("ConstructionPools");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.AntiAirGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AADPS")
                        .HasColumnType("double");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("AntiAirGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.Auxiliary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("AntiSubmarine")
                        .HasColumnType("int");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Oxygen")
                        .HasColumnType("int");

                    b.Property<int>("Reload")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int>("Torpedo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Auxiliaries");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+BattleshipGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("BattleshipGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+DestroyerGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DestroyerGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+DiveBomberPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AntiAir_Burst")
                        .HasColumnType("double");

                    b.Property<double>("AntiAir_DPS")
                        .HasColumnType("double");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Damage")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Speed")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DiveBomberPlanes");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+FighterPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AntiAir_Burst")
                        .HasColumnType("double");

                    b.Property<double>("AntiAir_DPS")
                        .HasColumnType("double");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Damage")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Speed")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("FighterPlanes");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+HeavyCruiserGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("HeavyCruiserGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+LargeCruiserGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("LargeCruiserGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+LightCruiserGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("LightCruiserGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+Seaplane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AntiAir_Burst")
                        .HasColumnType("double");

                    b.Property<double>("AntiAir_DPS")
                        .HasColumnType("double");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Damage")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Speed")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Seaplanes");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+TorpedoBomberPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AntiAir_Burst")
                        .HasColumnType("double");

                    b.Property<double>("AntiAir_DPS")
                        .HasColumnType("double");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Damage")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Speed")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("TorpedoBomberPlanes");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.SubmarineTorpedo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamagerPerTorpedo")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<string>("NumberOfTorpedoes")
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.Property<string>("TorpedoPower")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SubmarineTorpedoes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SubmarineTorpedo");
                });

            modelBuilder.Entity("AzurLaneClasses.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppliedToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Method")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("Protocol")
                        .HasColumnType("longtext");

                    b.Property<string>("QueryString")
                        .HasColumnType("longtext");

                    b.Property<string>("ResonseStatusCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("AzurLaneClasses.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BarrageId")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("DmgH")
                        .HasColumnType("double");

                    b.Property<double>("DmgL")
                        .HasColumnType("double");

                    b.Property<double>("DmgM")
                        .HasColumnType("double");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BarrageId");

                    b.ToTable("Round");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ConstructionAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Exchange")
                        .HasColumnType("longtext");

                    b.Property<string>("Heavy")
                        .HasColumnType("longtext");

                    b.Property<string>("Light")
                        .HasColumnType("longtext");

                    b.Property<string>("Limited")
                        .HasColumnType("longtext");

                    b.Property<string>("Special")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ConstructionAvailability");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Property<string>("ShipId")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BaseStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConstructionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EnhanceValueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level100RetrofitStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level100StatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level120RetrofitStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level120StatsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nation")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PixivId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Rarity")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ScrapValueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("StarsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ThumbnailImage")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TwitterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("VoiceActorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WebId")
                        .HasColumnType("char(36)");

                    b.HasKey("ShipId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("BaseStatsId");

                    b.HasIndex("ConstructionId");

                    b.HasIndex("EnhanceValueId");

                    b.HasIndex("Level100RetrofitStatsId");

                    b.HasIndex("Level100StatsId");

                    b.HasIndex("Level120RetrofitStatsId");

                    b.HasIndex("Level120StatsId");

                    b.HasIndex("PixivId");

                    b.HasIndex("ScrapValueId");

                    b.HasIndex("StarsId");

                    b.HasIndex("TwitterId");

                    b.HasIndex("VoiceActorId");

                    b.HasIndex("WebId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipArtist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipArtist");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipConstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AvailabilityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConstructionTime")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.ToTable("ShipConstruction");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipEnhanceValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<int>("Reload")
                        .HasColumnType("int");

                    b.Property<int>("Torpedo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipEnhanceValues");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipEquippableSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Max")
                        .HasColumnType("int");

                    b.Property<int>("MaxEfficiency")
                        .HasColumnType("int");

                    b.Property<int>("MinEfficiency")
                        .HasColumnType("int");

                    b.Property<string>("ShipId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipEquippableSlot");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipGalleryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ShipId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipGalleryItem");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipLimitBreaks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("LimitBreaks")
                        .HasColumnType("longtext");

                    b.Property<string>("ShipId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipLimitBreaks");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipPixiv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipPixiv");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("CN_Transcription")
                        .HasColumnType("longtext");

                    b.Property<string>("EN_Transcription")
                        .HasColumnType("longtext");

                    b.Property<string>("Event")
                        .HasColumnType("longtext");

                    b.Property<string>("JP_Transcription")
                        .HasColumnType("longtext");

                    b.Property<string>("ShipId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Skin")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipQuotes");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipScrapValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<int>("Medals")
                        .HasColumnType("int");

                    b.Property<int>("Oil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipScrapValues");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ShipId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipSkill");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ChibiUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("Live2dModel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ObtainedFrom")
                        .HasColumnType("longtext");

                    b.Property<string>("ShipId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipSkins");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipStars", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Stars")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipStars");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("Ammunition")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("AntiSubmarine")
                        .HasColumnType("int");

                    b.Property<string>("Armor")
                        .HasColumnType("longtext");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("HuntingRange")
                        .HasColumnType("longtext");

                    b.Property<int>("Luck")
                        .HasColumnType("int");

                    b.Property<int>("OilConsumption")
                        .HasColumnType("int");

                    b.Property<int>("Oxygen")
                        .HasColumnType("int");

                    b.Property<int>("Reload")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Torpedo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipStats");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipTwitter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipTwitter");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipVoiceActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipVoiceActor");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipWeb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipWeb");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.Torpedo", b =>
                {
                    b.HasBaseType("AzurLaneClasses.Equipment.SubmarineTorpedo");

                    b.Property<double>("PreloadDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("PreloadDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("PreloadDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Torpedo");
                });

            modelBuilder.Entity("AzurLaneClasses.Round", b =>
                {
                    b.HasOne("AzurLaneClasses.Barrage", null)
                        .WithMany("Rounds")
                        .HasForeignKey("BarrageId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.ShipArtist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "BaseStats")
                        .WithMany()
                        .HasForeignKey("BaseStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipConstruction", "Construction")
                        .WithMany()
                        .HasForeignKey("ConstructionId");

                    b.HasOne("AzurLaneClasses.Ship.ShipEnhanceValues", "EnhanceValue")
                        .WithMany()
                        .HasForeignKey("EnhanceValueId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level100RetrofitStats")
                        .WithMany()
                        .HasForeignKey("Level100RetrofitStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level100Stats")
                        .WithMany()
                        .HasForeignKey("Level100StatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level120RetrofitStats")
                        .WithMany()
                        .HasForeignKey("Level120RetrofitStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level120Stats")
                        .WithMany()
                        .HasForeignKey("Level120StatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipPixiv", "Pixiv")
                        .WithMany()
                        .HasForeignKey("PixivId");

                    b.HasOne("AzurLaneClasses.Ship.ShipScrapValues", "ScrapValue")
                        .WithMany()
                        .HasForeignKey("ScrapValueId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStars", "Stars")
                        .WithMany()
                        .HasForeignKey("StarsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipTwitter", "Twitter")
                        .WithMany()
                        .HasForeignKey("TwitterId");

                    b.HasOne("AzurLaneClasses.Ship.ShipVoiceActor", "VoiceActor")
                        .WithMany()
                        .HasForeignKey("VoiceActorId");

                    b.HasOne("AzurLaneClasses.Ship.ShipWeb", "Web")
                        .WithMany()
                        .HasForeignKey("WebId");

                    b.Navigation("Artist");

                    b.Navigation("BaseStats");

                    b.Navigation("Construction");

                    b.Navigation("EnhanceValue");

                    b.Navigation("Level100RetrofitStats");

                    b.Navigation("Level100Stats");

                    b.Navigation("Level120RetrofitStats");

                    b.Navigation("Level120Stats");

                    b.Navigation("Pixiv");

                    b.Navigation("ScrapValue");

                    b.Navigation("Stars");

                    b.Navigation("Twitter");

                    b.Navigation("VoiceActor");

                    b.Navigation("Web");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipConstruction", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.ConstructionAvailability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId");

                    b.Navigation("Availability");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipEquippableSlot", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("EquippableSlots")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipGalleryItem", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("Gallery")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipLimitBreaks", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("LimitBreaks")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipQuote", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("Quotes")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkill", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("Skills")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("Skins")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Barrage", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Navigation("EquippableSlots");

                    b.Navigation("Gallery");

                    b.Navigation("LimitBreaks");

                    b.Navigation("Quotes");

                    b.Navigation("Skills");

                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
