// <auto-generated />
using System;
using AzurLaneClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzurLaneClasses.Migrations
{
    [DbContext(typeof(AzurLaneDbContext))]
    [Migration("20210722222308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("AzurLaneClasses.ALEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CN_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EN_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("JP_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AzurLaneClasses.ALToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<bool>("WriteGrant")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ALTokens");
                });

            modelBuilder.Entity("AzurLaneClasses.CampaignLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CN_Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Chapter")
                        .HasColumnType("int");

                    b.Property<string>("EN_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("JP_Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CampaignLevels");
                });

            modelBuilder.Entity("AzurLaneClasses.ConstructionPool", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("AR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BB")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BC")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BM")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CL")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CV")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CVL")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<bool>("DD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SS")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WisdomCubes")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("ConstructionPools");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.AntiAirGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AADPS")
                        .HasColumnType("double");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("AntiAirGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.Auxiliary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("AntiSubmarine")
                        .HasColumnType("int");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Oxygen")
                        .HasColumnType("int");

                    b.Property<int>("Reload")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int>("Torpedo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Auxiliaries");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+BattleshipGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("BattleshipGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+DestroyerGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DestroyerGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+DiveBomberPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AntiAir_Burst")
                        .HasColumnType("double");

                    b.Property<double>("AntiAir_DPS")
                        .HasColumnType("double");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Damage")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Speed")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DiveBomberPlanes");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+FighterPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AntiAir_Burst")
                        .HasColumnType("double");

                    b.Property<double>("AntiAir_DPS")
                        .HasColumnType("double");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Damage")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Speed")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("FighterPlanes");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+HeavyCruiserGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("HeavyCruiserGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+LargeCruiserGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("LargeCruiserGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+LightCruiserGun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmmoType")
                        .HasColumnType("int");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamageCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerShot")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<double>("HeavyArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<double>("LightArmorDPS")
                        .HasColumnType("double");

                    b.Property<double>("MediumArmorDPS")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("RawDPS")
                        .HasColumnType("double");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<string>("Rounds")
                        .HasColumnType("longtext");

                    b.Property<double>("RoundsPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("VolleyTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("LightCruiserGuns");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+Seaplane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AntiAir_Burst")
                        .HasColumnType("double");

                    b.Property<double>("AntiAir_DPS")
                        .HasColumnType("double");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Damage")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Speed")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Seaplanes");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.EquipmentOverrides+TorpedoBomberPlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AntiAir_Burst")
                        .HasColumnType("double");

                    b.Property<double>("AntiAir_DPS")
                        .HasColumnType("double");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Damage")
                        .HasColumnType("int");

                    b.Property<int>("Crash_Speed")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("TorpedoBomberPlanes");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.SubmarineTorpedo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Angle")
                        .HasColumnType("int");

                    b.Property<string>("Attribute")
                        .HasColumnType("longtext");

                    b.Property<int>("DamagerPerTorpedo")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<string>("NumberOfTorpedoes")
                        .HasColumnType("longtext");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<double>("Reload")
                        .HasColumnType("double");

                    b.Property<int>("Spread")
                        .HasColumnType("int");

                    b.Property<double>("SurfaceDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("SurfaceDPS_MediumArmor")
                        .HasColumnType("double");

                    b.Property<string>("TorpedoPower")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SubmarineTorpedoes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SubmarineTorpedo");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("BaseStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultChibiImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DefaultFullImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EquippableTypeSlot1")
                        .HasColumnType("int");

                    b.Property<int>("EquippableTypeSlot2")
                        .HasColumnType("int");

                    b.Property<int>("EquippableTypeSlot3")
                        .HasColumnType("int");

                    b.Property<bool>("HasLive2DModel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IconImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Level100RetrofitStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level100StatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level120RetrofitStatsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level120StatsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("ShipId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VoiceActor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaseStatsId");

                    b.HasIndex("Level100RetrofitStatsId");

                    b.HasIndex("Level100StatsId");

                    b.HasIndex("Level120RetrofitStatsId");

                    b.HasIndex("Level120StatsId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipClasses");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChibiImage")
                        .HasColumnType("longtext");

                    b.Property<string>("FullImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_Chinese")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_English")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_Japanese")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ShipId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipSkins");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("Ammunition")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("AntiSubmarine")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Luck")
                        .HasColumnType("int");

                    b.Property<int>("OilConsumption")
                        .HasColumnType("int");

                    b.Property<int>("Oxygen")
                        .HasColumnType("int");

                    b.Property<int>("Reload")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Torpedo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipStats");
                });

            modelBuilder.Entity("AzurLaneClasses.Equipment.Torpedo", b =>
                {
                    b.HasBaseType("AzurLaneClasses.Equipment.SubmarineTorpedo");

                    b.Property<double>("PreloadDPS_HeavyArmor")
                        .HasColumnType("double");

                    b.Property<double>("PreloadDPS_LightArmor")
                        .HasColumnType("double");

                    b.Property<double>("PreloadDPS_MediumArmor")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Torpedo");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "BaseStats")
                        .WithMany()
                        .HasForeignKey("BaseStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level100RetrofitStats")
                        .WithMany()
                        .HasForeignKey("Level100RetrofitStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level100Stats")
                        .WithMany()
                        .HasForeignKey("Level100StatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level120RetrofitStats")
                        .WithMany()
                        .HasForeignKey("Level120RetrofitStatsId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level120Stats")
                        .WithMany()
                        .HasForeignKey("Level120StatsId");

                    b.Navigation("BaseStats");

                    b.Navigation("Level100RetrofitStats");

                    b.Navigation("Level100Stats");

                    b.Navigation("Level120RetrofitStats");

                    b.Navigation("Level120Stats");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("Skins")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
