// <auto-generated />
using System;
using AzurLaneClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzurLaneClasses.Migrations
{
    [DbContext(typeof(AzurLaneDbContext))]
    partial class AzurLaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("AzurLaneClasses.ALEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CN_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EN_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("JP_Period")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("BaseStatsIdId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultChibiImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DefaultFullImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EquippableTypeSlot1")
                        .HasColumnType("int");

                    b.Property<int>("EquippableTypeSlot2")
                        .HasColumnType("int");

                    b.Property<int>("EquippableTypeSlot3")
                        .HasColumnType("int");

                    b.Property<bool>("HasLive2DModel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IconImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Level100RetrofitStatsIdId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level100StatsIdId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level120RetrofitStatsIdId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Level120StatsIdId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nation")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("ShipId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VoiceActor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaseStatsIdId");

                    b.HasIndex("Level100RetrofitStatsIdId");

                    b.HasIndex("Level100StatsIdId");

                    b.HasIndex("Level120RetrofitStatsIdId");

                    b.HasIndex("Level120StatsIdId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShipClasses");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChibiImage")
                        .HasColumnType("longtext");

                    b.Property<string>("FullImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_Chinese")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_English")
                        .HasColumnType("longtext");

                    b.Property<string>("Name_Japanese")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ShipId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipSkins");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("Ammunition")
                        .HasColumnType("int");

                    b.Property<int>("AntiAir")
                        .HasColumnType("int");

                    b.Property<int>("AntiSubmarine")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Aviation")
                        .HasColumnType("int");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Luck")
                        .HasColumnType("int");

                    b.Property<int>("OilConsumption")
                        .HasColumnType("int");

                    b.Property<int>("Oxygen")
                        .HasColumnType("int");

                    b.Property<int>("Reload")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Torpedo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipStats");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "BaseStatsId")
                        .WithMany()
                        .HasForeignKey("BaseStatsIdId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level100RetrofitStatsId")
                        .WithMany()
                        .HasForeignKey("Level100RetrofitStatsIdId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level100StatsId")
                        .WithMany()
                        .HasForeignKey("Level100StatsIdId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level120RetrofitStatsId")
                        .WithMany()
                        .HasForeignKey("Level120RetrofitStatsIdId");

                    b.HasOne("AzurLaneClasses.Ship.ShipStats", "Level120StatsId")
                        .WithMany()
                        .HasForeignKey("Level120StatsIdId");

                    b.Navigation("BaseStatsId");

                    b.Navigation("Level100RetrofitStatsId");

                    b.Navigation("Level100StatsId");

                    b.Navigation("Level120RetrofitStatsId");

                    b.Navigation("Level120StatsId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.ShipSkin", b =>
                {
                    b.HasOne("AzurLaneClasses.Ship.Ship", null)
                        .WithMany("Skins")
                        .HasForeignKey("ShipId");
                });

            modelBuilder.Entity("AzurLaneClasses.Ship.Ship", b =>
                {
                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
