name: Availability Checker

on:
  schedule:
  - cron: "*/5 * * * *"
  
jobs:
  test_routes:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Execute Routes
      run: dotnet test --verbosity normal
